version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: pip

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci

  - package-ecosystem: npm
    directory: /monitor/device/web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    groups:
      web-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: npm

  - package-ecosystem: npm
    directory: /infra/cloudflare
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    groups:
      pulumi-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: npm
