sonar.organization=mzworthington
sonar.projectKey=mzworthington_gpio-build-monitor
sonar.sources=monitor/api,monitor/device/web,monitor/device/pi,monitor/device/menu-bar,monitor/device/eink/apps,monitor/device/eink/host_test,monitor/device/eink/include,monitor/device/eink/src,monitor/device/eink/test,infra,test,bin,.github
sonar.exclusions=.github/workflows/**
sonar.coverage.exclusions=monitor/device/web/**,monitor/device/eink/**
sonar.python.coverage.reportPaths=coverage.xml
